"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.core.urlresolvers import reverse_lazy

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v1kyc0ocxh0e-pt-zl(uoz=7i*_#tqp$*7*s$5*nv)fg7lh$m)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = (
    'flat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_facebook',
    'facebook',
    'bootstrapform',
    'djcelery',
    'twitter',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)



TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.contrib.messages.context_processors.messages",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.static",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
    "django.core.context_processors.tz",
    'django_facebook.context_processors.facebook',
)

ROOT_URLCONF = 'app.urls'

PACKAGE_ROOT = os.path.abspath(os.path.dirname(__file__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PACKAGE_ROOT, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = (
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
)


WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

PROJECT_NAME = DB_USER = DB_NAME = "trabajo_grado"
DB_PASS = ":)J#lv:taaNX)zW7cY{wj(4~]@rsdfasJHKJiuiuyui!!?==)(/&423+cka[kDk-.>CZ^Jj!z\9zt37!Hl"


DATABASES = {
    "default": {
        # Add "postgresql_psycopg2", "mysql", "sqlite3" or "oracle".
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        # DB name or path to database file if using sqlite3.
        "NAME": DB_USER,
        # Not used with sqlite3.
        "USER": DB_NAME,
        # Not used with sqlite3.
        "PASSWORD": DB_PASS,
        # Set to empty string for localhost. Not used with sqlite3.
        "HOST": "localhost",
        # Set to empty string for default. Not used with sqlite3.
        "PORT": "5432",
    },
    'ahorrando': {
        'NAME': 'ahorrando',
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        'USER': 'ahorrando',
        'PASSWORD': DB_PASS
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'



AUTHENTICATION_BACKENDS = (
    'django_facebook.auth_backends.FacebookBackend',
    'django.contrib.auth.backends.ModelBackend',
)

AUTH_USER_MODEL = 'django_facebook.FacebookCustomUser'
AUTH_PROFILE_MODULE = 'django_facebook.FacebookProfile'


STATIC_URL = '/static/'
APPEND_SLASH = True

FACEBOOK_APP_ID = "503842489778133"
FACEBOOK_APP_SECRET = "e8e2d773f6e75f3823ab9d56def057b9"
FACEBOOK_PAGE_ID =   "136912349730019"
# FACEBOOK_PAGE_ID =   "279756545517007"

FORMS_USE_HTML5 = True


TWITTER_KEY = 'zta3TPBeOGxQeswPeMKbbW7Os'
TWITTER_SECRET = 'dCcJ21QRTeSWJ5wZxmwr91336AofHeDkvAY5yRkSG8S9GcHISG'
TWITTER_ACCOUNT = 'arley_wilches'
LOGOUT_REDIRECT_URL = reverse_lazy('admin')


# AUTH_USER_MODEL = 'auth.User'
import djcelery
djcelery.setup_loader()
# Internationalization
# https://docs.djangoproject.com/en/1.6/topics/i18n/
USE_TZ = True
TIME_ZONE = 'America/Bogota'
CELERY_TIMEZONE = 'America/Bogota'
CELERY_ENABLE_UTC = True


BROKER_URL = 'amqp://guest:guest@localhost:5672'

CELERY_RESULT_BACKEND = 'redis://localhost/1'

# CELERY_RESULT_BACKEND = "mongodb"
# CELERY_MONGODB_BACKEND_SETTINGS = {
#     "host": "127.0.0.1",
#     "port": 27017,
#     "database": "celery",
#     "taskmeta_collection": "my_taskmeta" # Collection name to use for task output
# }

CELERY_IMPORTS = ("tasks.tasks")

# The default Django db scheduler
CELERYBEAT_SCHEDULER = "djcelery.schedulers.DatabaseScheduler"
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
